Cleaning up publish

diff --git a/cmd/shell-integration.sh.tmpl b/cmd/shell-integration.sh.tmpl
--- a/cmd/shell-integration.sh.tmpl
+++ b/cmd/shell-integration.sh.tmpl
@@ -1,10 +1,10 @@
 jump_post() {
-    if [ -z "${WRITING_REPO_DIRPATH}" ]; then
-        echo "Error: WRITING_REPO_DIRPATH var must point to your writing repo" >&2
+    if [ -z "${{{.WritingDirEnvVar}}}" ]; then
+        echo "Error: {{.WritingDirEnvVar}} var must point to your writing repo" >&2
         return 1
     fi
 
-    find_post_output="$({{.BinaryName}} find "${WRITING_REPO_DIRPATH}" "${@}")"
+    find_post_output="$({{.BinaryName}} find "${{{.WritingDirEnvVar}}}" "${@}")"
     find_post_exit_code=$?
     
     if [ $find_post_exit_code -eq 2 ]; then
@@ -25,7 +25,7 @@ jump_post() {
         return 1
     fi
 
-    cd "${WRITING_REPO_DIRPATH}"
+    cd "${{{.WritingDirEnvVar}}}"
 
     if ! git checkout "${post_branch}"; then
         echo "Error: An error occurred checking out branch '${post_branch}'" >&2
@@ -47,12 +47,12 @@ edit_post() {
 }
 
 new_post() {
-    if [ -z "${WRITING_REPO_DIRPATH}" ]; then
-        echo "Error: WRITING_REPO_DIRPATH var must point to your writing repo" >&2
+    if [ -z "${{{.WritingDirEnvVar}}}" ]; then
+        echo "Error: {{.WritingDirEnvVar}} var must point to your writing repo" >&2
         return 1
     fi
 
-    new_post_dirpath="$({{.BinaryName}} add "${WRITING_REPO_DIRPATH}" "${@}")"
+    new_post_dirpath="$({{.BinaryName}} add "${{{.WritingDirEnvVar}}}" "${@}")"
     new_post_exit_code=$?
     
     if [ $new_post_exit_code -eq 2 ]; then
@@ -68,11 +68,11 @@ new_post() {
 }
 
 publish_post() {
-    if [ -z "${WRITING_REPO_DIRPATH}" ]; then
-        echo "Error: WRITING_REPO_DIRPATH var must point to your writing repo" >&2
+    if [ -z "${{{.WritingDirEnvVar}}}" ]; then
+        echo "Error: {{.WritingDirEnvVar}} var must point to your writing repo" >&2
         return 1
     fi
 
-    cd "${WRITING_REPO_DIRPATH}"
+    cd "${{{.WritingDirEnvVar}}}"
     {{.BinaryName}} publish
 }
