Created 'add' command

diff --git a/cmd/shell-integration.sh.tmpl b/cmd/shell-integration.sh.tmpl
--- a/cmd/shell-integration.sh.tmpl
+++ b/cmd/shell-integration.sh.tmpl
@@ -39,3 +39,24 @@ find_post() {
 
     ${EDITOR} post.md
 }
+
+new_post() {
+    if [ -z "${WRITING_REPO_DIRPATH}" ]; then
+        echo "Error: WRITING_REPO_DIRPATH var must point to your writing repo" >&2
+        return 1
+    fi
+
+    new_post_dirpath="$({{.BinaryName}} add "${WRITING_REPO_DIRPATH}" "${@}")"
+    new_post_exit_code=$?
+    
+    if [ $new_post_exit_code -eq 2 ]; then
+        # User cancelled - exit silently
+        return 2
+    elif [ $new_post_exit_code -ne 0 ]; then
+        echo "Error: {{.BinaryName}} add failed" >&2
+        return 1
+    fi
+
+    cd "${new_post_dirpath}"
+    ${EDITOR} post.md
+}
